# Generated by Django 3.2.6 on 2021-12-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0.0, verbose_name='Salary'),
        ),
    ]
